/* SPDX-License-Identifier: MIT
 *
 * Copyright 2016-2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 */

/************************************
 ** This is an auto-generated file **
 **       DO NOT EDIT BELOW        **
 ************************************/

#ifndef ASIC_REG_PCIE_WRAP_MASKS_H_
#define ASIC_REG_PCIE_WRAP_MASKS_H_

/*
 *****************************************
 *   PCIE_WRAP
 *   (Prototype: PCIE_WRAP)
 *****************************************
 */

/* PCIE_WRAP_INTR_GEN_MASK_MIN_ADDR */
#define PCIE_WRAP_INTR_GEN_MASK_MIN_ADDR_ADDR_SHIFT 0
#define PCIE_WRAP_INTR_GEN_MASK_MIN_ADDR_ADDR_MASK 0xFFFFFFFF

/* PCIE_WRAP_INTR_GEN_MASK_MAX_ADDR */
#define PCIE_WRAP_INTR_GEN_MASK_MAX_ADDR_ADDR_SHIFT 0
#define PCIE_WRAP_INTR_GEN_MASK_MAX_ADDR_ADDR_MASK 0xFFFFFFFF

/* PCIE_WRAP_INTR_GEN_MASK_TIMER */
#define PCIE_WRAP_INTR_GEN_MASK_TIMER_TIMER_SHIFT 0
#define PCIE_WRAP_INTR_GEN_MASK_TIMER_TIMER_MASK 0xFFFFFFFF

/* PCIE_WRAP_INTR_GEN_MASK_CTRL */
#define PCIE_WRAP_INTR_GEN_MASK_CTRL_EN_SHIFT 0
#define PCIE_WRAP_INTR_GEN_MASK_CTRL_EN_MASK 0x1
#define PCIE_WRAP_INTR_GEN_MASK_CTRL_THRESHOLD_SHIFT 1
#define PCIE_WRAP_INTR_GEN_MASK_CTRL_THRESHOLD_MASK 0x3FE

/* PCIE_WRAP_MSIX_DOORBELL_OFF_ADDR */
#define PCIE_WRAP_MSIX_DOORBELL_OFF_ADDR_ADDR_SHIFT 0
#define PCIE_WRAP_MSIX_DOORBELL_OFF_ADDR_ADDR_MASK 0xFFFFFFFF

/* PCIE_WRAP_MSIX_MASK_CTRL */
#define PCIE_WRAP_MSIX_MASK_CTRL_EN_SHIFT 0
#define PCIE_WRAP_MSIX_MASK_CTRL_EN_MASK 0x1
#define PCIE_WRAP_MSIX_MASK_CTRL_RESP_SHIFT 1
#define PCIE_WRAP_MSIX_MASK_CTRL_RESP_MASK 0x2
#define PCIE_WRAP_MSIX_MASK_CTRL_THRESHOLD_SHIFT 2
#define PCIE_WRAP_MSIX_MASK_CTRL_THRESHOLD_MASK 0x3FFFC

/* PCIE_WRAP_PHY_FW_SRAM_ADDR_L */
#define PCIE_WRAP_PHY_FW_SRAM_ADDR_L_ADDR_SHIFT 0
#define PCIE_WRAP_PHY_FW_SRAM_ADDR_L_ADDR_MASK 0xFFFFFFFF

/* PCIE_WRAP_PHY_FW_SRAM_ADDR_H */
#define PCIE_WRAP_PHY_FW_SRAM_ADDR_H_ADDR_SHIFT 0
#define PCIE_WRAP_PHY_FW_SRAM_ADDR_H_ADDR_MASK 0xFFFFFFFF

/* PCIE_WRAP_PHY_FW_SRAM_CFG_ADDR */
#define PCIE_WRAP_PHY_FW_SRAM_CFG_ADDR_EN_SHIFT 0
#define PCIE_WRAP_PHY_FW_SRAM_CFG_ADDR_EN_MASK 0x1

/* PCIE_WRAP_MSIX_GW */
#define PCIE_WRAP_MSIX_GW_EN_SHIFT 0
#define PCIE_WRAP_MSIX_GW_EN_MASK 0x1
#define PCIE_WRAP_MSIX_GW_INTR_MASK_SHIFT 1
#define PCIE_WRAP_MSIX_GW_INTR_MASK_MASK 0x2
#define PCIE_WRAP_MSIX_GW_ERR_RESP_SHIFT 2
#define PCIE_WRAP_MSIX_GW_ERR_RESP_MASK 0x4

/* PCIE_WRAP_MSIX_GW_VEC */
#define PCIE_WRAP_MSIX_GW_VEC_VAL_SHIFT 0
#define PCIE_WRAP_MSIX_GW_VEC_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MSIX_GW_INTR */
#define PCIE_WRAP_MSIX_GW_INTR_INTR_SHIFT 0
#define PCIE_WRAP_MSIX_GW_INTR_INTR_MASK 0x1

/* PCIE_WRAP_MSIX_GW_TABLE */
#define PCIE_WRAP_MSIX_GW_TABLE_VAL_SHIFT 0
#define PCIE_WRAP_MSIX_GW_TABLE_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_VUART_RX */
#define PCIE_WRAP_VUART_RX_VAL_SHIFT 0
#define PCIE_WRAP_VUART_RX_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_VUART_TX */
#define PCIE_WRAP_VUART_TX_VAL_SHIFT 0
#define PCIE_WRAP_VUART_TX_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MSI_GW_BLOCK */
#define PCIE_WRAP_MSI_GW_BLOCK_EN_SHIFT 0
#define PCIE_WRAP_MSI_GW_BLOCK_EN_MASK 0x1

/* PCIE_WRAP_PHY_FW_FSM_SIZE */
#define PCIE_WRAP_PHY_FW_FSM_SIZE_VAL_SHIFT 0
#define PCIE_WRAP_PHY_FW_FSM_SIZE_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_HOST_ACCESS_TERMINATION */
#define PCIE_WRAP_HOST_ACCESS_TERMINATION_EN_SHIFT 0
#define PCIE_WRAP_HOST_ACCESS_TERMINATION_EN_MASK 0x1
#define PCIE_WRAP_HOST_ACCESS_TERMINATION_BRESP_VAL_SHIFT 1
#define PCIE_WRAP_HOST_ACCESS_TERMINATION_BRESP_VAL_MASK 0x6
#define PCIE_WRAP_HOST_ACCESS_TERMINATION_RRSEP_VAL_SHIFT 3
#define PCIE_WRAP_HOST_ACCESS_TERMINATION_RRSEP_VAL_MASK 0x18

/* PCIE_WRAP_ILLEGAL_LBW_REQ_CTRL */
#define PCIE_WRAP_ILLEGAL_LBW_REQ_CTRL_EN_SHIFT 0
#define PCIE_WRAP_ILLEGAL_LBW_REQ_CTRL_EN_MASK 0x1
#define PCIE_WRAP_ILLEGAL_LBW_REQ_CTRL_MASK_INTR_SHIFT 1
#define PCIE_WRAP_ILLEGAL_LBW_REQ_CTRL_MASK_INTR_MASK 0x2
#define PCIE_WRAP_ILLEGAL_LBW_REQ_CTRL_RESP_VAL_SHIFT 2
#define PCIE_WRAP_ILLEGAL_LBW_REQ_CTRL_RESP_VAL_MASK 0xC

/* PCIE_WRAP_ILLEGAL_LBW_REQ_ADDR */
#define PCIE_WRAP_ILLEGAL_LBW_REQ_ADDR_VAL_SHIFT 0
#define PCIE_WRAP_ILLEGAL_LBW_REQ_ADDR_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_ILLEGAL_LBW_REQ_INTR */
#define PCIE_WRAP_ILLEGAL_LBW_REQ_INTR_INTR_SHIFT 0
#define PCIE_WRAP_ILLEGAL_LBW_REQ_INTR_INTR_MASK 0x1

/* PCIE_WRAP_OUTBOUND_ADDR_LSB */
#define PCIE_WRAP_OUTBOUND_ADDR_LSB_OVRD_EN_SHIFT 0
#define PCIE_WRAP_OUTBOUND_ADDR_LSB_OVRD_EN_MASK 0x1
#define PCIE_WRAP_OUTBOUND_ADDR_LSB_IND_MASK_SHIFT 1
#define PCIE_WRAP_OUTBOUND_ADDR_LSB_IND_MASK_MASK 0x2
#define PCIE_WRAP_OUTBOUND_ADDR_LSB_IND_SHIFT 2
#define PCIE_WRAP_OUTBOUND_ADDR_LSB_IND_MASK 0x4

/* PCIE_WRAP_LBW_WSTRB_OVRD */
#define PCIE_WRAP_LBW_WSTRB_OVRD_EN_SHIFT 0
#define PCIE_WRAP_LBW_WSTRB_OVRD_EN_MASK 0x1

/* PCIE_WRAP_LBW_GW_ADDR */
#define PCIE_WRAP_LBW_GW_ADDR_ADDR_SHIFT 0
#define PCIE_WRAP_LBW_GW_ADDR_ADDR_MASK 0xFFFFFFFF

/* PCIE_WRAP_LBW_GW_DATA */
#define PCIE_WRAP_LBW_GW_DATA_DATA_SHIFT 0
#define PCIE_WRAP_LBW_GW_DATA_DATA_MASK 0xFFFFFFFF

/* PCIE_WRAP_LBW_GW_GO */
#define PCIE_WRAP_LBW_GW_GO_GO_SHIFT 0
#define PCIE_WRAP_LBW_GW_GO_GO_MASK 0x1

/* PCIE_WRAP_LBW_GW_STATUS */
#define PCIE_WRAP_LBW_GW_STATUS_STATUS_SHIFT 0
#define PCIE_WRAP_LBW_GW_STATUS_STATUS_MASK 0x1

/* PCIE_WRAP_OUTBOUND_OUTSTANDING */
#define PCIE_WRAP_OUTBOUND_OUTSTANDING_RD_SHIFT 0
#define PCIE_WRAP_OUTBOUND_OUTSTANDING_RD_MASK 0x1FF
#define PCIE_WRAP_OUTBOUND_OUTSTANDING_WR_SHIFT 9
#define PCIE_WRAP_OUTBOUND_OUTSTANDING_WR_MASK 0x3FE00

/* PCIE_WRAP_MASK_REQ */
#define PCIE_WRAP_MASK_REQ_TOWARDS_LBW_SHIFT 0
#define PCIE_WRAP_MASK_REQ_TOWARDS_LBW_MASK 0x1
#define PCIE_WRAP_MASK_REQ_FROM_LBW_SHIFT 1
#define PCIE_WRAP_MASK_REQ_FROM_LBW_MASK 0x2
#define PCIE_WRAP_MASK_REQ_TOWARDS_HBW_SHIFT 2
#define PCIE_WRAP_MASK_REQ_TOWARDS_HBW_MASK 0x4
#define PCIE_WRAP_MASK_REQ_FROM_HBW_SHIFT 3
#define PCIE_WRAP_MASK_REQ_FROM_HBW_MASK 0x8
#define PCIE_WRAP_MASK_REQ_DBG_SHIFT 4
#define PCIE_WRAP_MASK_REQ_DBG_MASK 0x10
#define PCIE_WRAP_MASK_REQ_TRACE_SHIFT 5
#define PCIE_WRAP_MASK_REQ_TRACE_MASK 0x20
#define PCIE_WRAP_MASK_REQ_ECT_SHIFT 6
#define PCIE_WRAP_MASK_REQ_ECT_MASK 0x40

/* PCIE_WRAP_ONE_IN_FLIGHT */
#define PCIE_WRAP_ONE_IN_FLIGHT_LBW_BLOCK_HBW_EN_SHIFT 0
#define PCIE_WRAP_ONE_IN_FLIGHT_LBW_BLOCK_HBW_EN_MASK 0x1
#define PCIE_WRAP_ONE_IN_FLIGHT_HBW_BLOCK_LBW_EN_SHIFT 1
#define PCIE_WRAP_ONE_IN_FLIGHT_HBW_BLOCK_LBW_EN_MASK 0x2

/* PCIE_WRAP_IND_AWPROT */
#define PCIE_WRAP_IND_AWPROT_VAL_SHIFT 0
#define PCIE_WRAP_IND_AWPROT_VAL_MASK 0x7

/* PCIE_WRAP_SLV_AWMISC_INFO */
#define PCIE_WRAP_SLV_AWMISC_INFO_VAL_SHIFT 0
#define PCIE_WRAP_SLV_AWMISC_INFO_VAL_MASK 0x3FFFFF

/* PCIE_WRAP_SLV_AWMISC_INFO_HDR_34DW */
#define PCIE_WRAP_SLV_AWMISC_INFO_HDR_34DW_VAL_SHIFT 0
#define PCIE_WRAP_SLV_AWMISC_INFO_HDR_34DW_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_SLV_AWMISC_INFO_P_TAG */
#define PCIE_WRAP_SLV_AWMISC_INFO_P_TAG_VAL_SHIFT 0
#define PCIE_WRAP_SLV_AWMISC_INFO_P_TAG_VAL_MASK 0x3FF

/* PCIE_WRAP_SLV_AWMISC_INFO_ATU_BYPAS */
#define PCIE_WRAP_SLV_AWMISC_INFO_ATU_BYPAS_VAL_SHIFT 0
#define PCIE_WRAP_SLV_AWMISC_INFO_ATU_BYPAS_VAL_MASK 0x1

/* PCIE_WRAP_SLV_AWMISC_INFO_FUNC_NUM */
#define PCIE_WRAP_SLV_AWMISC_INFO_FUNC_NUM_VAL_SHIFT 0
#define PCIE_WRAP_SLV_AWMISC_INFO_FUNC_NUM_VAL_MASK 0x1

/* PCIE_WRAP_SLV_AWMISC_INFO_VFUNC_ACT */
#define PCIE_WRAP_SLV_AWMISC_INFO_VFUNC_ACT_VAL_SHIFT 0
#define PCIE_WRAP_SLV_AWMISC_INFO_VFUNC_ACT_VAL_MASK 0x1

/* PCIE_WRAP_SLV_AWMISC_INFO_VFUNC_NUM */
#define PCIE_WRAP_SLV_AWMISC_INFO_VFUNC_NUM_VAL_SHIFT 0
#define PCIE_WRAP_SLV_AWMISC_INFO_VFUNC_NUM_VAL_MASK 0x7F

/* PCIE_WRAP_SLV_AWMISC_INFO_TLPPRFX */
#define PCIE_WRAP_SLV_AWMISC_INFO_TLPPRFX_VAL_SHIFT 0
#define PCIE_WRAP_SLV_AWMISC_INFO_TLPPRFX_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_SLV_ARMISC_INFO */
#define PCIE_WRAP_SLV_ARMISC_INFO_VAL_SHIFT 0
#define PCIE_WRAP_SLV_ARMISC_INFO_VAL_MASK 0x3FFFFF

/* PCIE_WRAP_SLV_ARMISC_INFO_TLPPRFX */
#define PCIE_WRAP_SLV_ARMISC_INFO_TLPPRFX_VAL_SHIFT 0
#define PCIE_WRAP_SLV_ARMISC_INFO_TLPPRFX_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_SLV_ARMISC_INFO_ATU_BYP */
#define PCIE_WRAP_SLV_ARMISC_INFO_ATU_BYP_VAL_SHIFT 0
#define PCIE_WRAP_SLV_ARMISC_INFO_ATU_BYP_VAL_MASK 0x1

/* PCIE_WRAP_SLV_ARMISC_INFO_FUNC_NUM */
#define PCIE_WRAP_SLV_ARMISC_INFO_FUNC_NUM_VAL_SHIFT 0
#define PCIE_WRAP_SLV_ARMISC_INFO_FUNC_NUM_VAL_MASK 0x1

/* PCIE_WRAP_SLV_ARMISC_INFO_VFUNC_ACT */
#define PCIE_WRAP_SLV_ARMISC_INFO_VFUNC_ACT_IND_SHIFT 0
#define PCIE_WRAP_SLV_ARMISC_INFO_VFUNC_ACT_IND_MASK 0x1

/* PCIE_WRAP_SLV_ARMISC_INFO_VFUNC_NUM */
#define PCIE_WRAP_SLV_ARMISC_INFO_VFUNC_NUM_VAL_SHIFT 0
#define PCIE_WRAP_SLV_ARMISC_INFO_VFUNC_NUM_VAL_MASK 0x7F

/* PCIE_WRAP_MESO_FIFO_CTRL */
#define PCIE_WRAP_MESO_FIFO_CTRL_W_ENABLE_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_CTRL_W_ENABLE_MASK 0x1
#define PCIE_WRAP_MESO_FIFO_CTRL_W_STATS_CLEAR_SHIFT 1
#define PCIE_WRAP_MESO_FIFO_CTRL_W_STATS_CLEAR_MASK 0x2
#define PCIE_WRAP_MESO_FIFO_CTRL_W_FLUSH_SHIFT 2
#define PCIE_WRAP_MESO_FIFO_CTRL_W_FLUSH_MASK 0x4
#define PCIE_WRAP_MESO_FIFO_CTRL_W_LFSR_SET_SHIFT 3
#define PCIE_WRAP_MESO_FIFO_CTRL_W_LFSR_SET_MASK 0x8
#define PCIE_WRAP_MESO_FIFO_CTRL_W_BP_EN_SHIFT 4
#define PCIE_WRAP_MESO_FIFO_CTRL_W_BP_EN_MASK 0x10
#define PCIE_WRAP_MESO_FIFO_CTRL_R_ENABLE_SHIFT 5
#define PCIE_WRAP_MESO_FIFO_CTRL_R_ENABLE_MASK 0x20
#define PCIE_WRAP_MESO_FIFO_CTRL_R_FLUSH_SHIFT 6
#define PCIE_WRAP_MESO_FIFO_CTRL_R_FLUSH_MASK 0x40
#define PCIE_WRAP_MESO_FIFO_CTRL_R_STATS_CLEAR_SHIFT 7
#define PCIE_WRAP_MESO_FIFO_CTRL_R_STATS_CLEAR_MASK 0x80
#define PCIE_WRAP_MESO_FIFO_CTRL_R_LFSR_SET_SHIFT 8
#define PCIE_WRAP_MESO_FIFO_CTRL_R_LFSR_SET_MASK 0x100
#define PCIE_WRAP_MESO_FIFO_CTRL_R_BP_EN_SHIFT 9
#define PCIE_WRAP_MESO_FIFO_CTRL_R_BP_EN_MASK 0x200

/* PCIE_WRAP_MESO_FIFO_W_LFSR_POLY */
#define PCIE_WRAP_MESO_FIFO_W_LFSR_POLY_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_W_LFSR_POLY_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MESO_FIFO_R_LFSR_POLY */
#define PCIE_WRAP_MESO_FIFO_R_LFSR_POLY_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_R_LFSR_POLY_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MESO_FIFO_W_PUSH_CNT */
#define PCIE_WRAP_MESO_FIFO_W_PUSH_CNT_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_W_PUSH_CNT_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MESO_FIFO_W_BP_CNT */
#define PCIE_WRAP_MESO_FIFO_W_BP_CNT_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_W_BP_CNT_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MESO_FIFO_R_ERR_CNT */
#define PCIE_WRAP_MESO_FIFO_R_ERR_CNT_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_R_ERR_CNT_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MESO_FIFO_R_POP_CNT */
#define PCIE_WRAP_MESO_FIFO_R_POP_CNT_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_R_POP_CNT_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MESO_FIFO_W_LFSR */
#define PCIE_WRAP_MESO_FIFO_W_LFSR_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_W_LFSR_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MESO_FIFO_R_LFSR */
#define PCIE_WRAP_MESO_FIFO_R_LFSR_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_R_LFSR_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MESO_FIFO_W_PUSH_LFSR */
#define PCIE_WRAP_MESO_FIFO_W_PUSH_LFSR_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_W_PUSH_LFSR_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MESO_FIFO_R_POP_LFSR */
#define PCIE_WRAP_MESO_FIFO_R_POP_LFSR_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_R_POP_LFSR_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MESO_FIFO_W_BP_PERIOD */
#define PCIE_WRAP_MESO_FIFO_W_BP_PERIOD_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_W_BP_PERIOD_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MESO_FIFO_R_BP_PERIOD */
#define PCIE_WRAP_MESO_FIFO_R_BP_PERIOD_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_R_BP_PERIOD_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_MESO_FIFO_W_USED_CNT */
#define PCIE_WRAP_MESO_FIFO_W_USED_CNT_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_W_USED_CNT_VAL_MASK 0x7

/* PCIE_WRAP_MESO_FIFO_R_USED_CNT */
#define PCIE_WRAP_MESO_FIFO_R_USED_CNT_VAL_SHIFT 0
#define PCIE_WRAP_MESO_FIFO_R_USED_CNT_VAL_MASK 0x7

/* PCIE_WRAP_P2P_TABLE */
#define PCIE_WRAP_P2P_TABLE_VLD_SHIFT 0
#define PCIE_WRAP_P2P_TABLE_VLD_MASK 0x1
#define PCIE_WRAP_P2P_TABLE_REQ_ID_SHIFT 1
#define PCIE_WRAP_P2P_TABLE_REQ_ID_MASK 0x1FFFE
#define PCIE_WRAP_P2P_TABLE_PROT_SHIFT 17
#define PCIE_WRAP_P2P_TABLE_PROT_MASK 0xE0000

/* PCIE_WRAP_P2P_EN */
#define PCIE_WRAP_P2P_EN_EN_SHIFT 0
#define PCIE_WRAP_P2P_EN_EN_MASK 0x1
#define PCIE_WRAP_P2P_EN_MASK_INTR_SHIFT 1
#define PCIE_WRAP_P2P_EN_MASK_INTR_MASK 0x2

/* PCIE_WRAP_P2P_REQ_ID */
#define PCIE_WRAP_P2P_REQ_ID_ID_SHIFT 0
#define PCIE_WRAP_P2P_REQ_ID_ID_MASK 0xFFFF

/* PCIE_WRAP_P2P_INTR */
#define PCIE_WRAP_P2P_INTR_INTR_SHIFT 0
#define PCIE_WRAP_P2P_INTR_INTR_MASK 0x1

/* PCIE_WRAP_P2P_TERMINATE_RESP */
#define PCIE_WRAP_P2P_TERMINATE_RESP_BRESP_SHIFT 0
#define PCIE_WRAP_P2P_TERMINATE_RESP_BRESP_MASK 0x3
#define PCIE_WRAP_P2P_TERMINATE_RESP_RRESP_SHIFT 2
#define PCIE_WRAP_P2P_TERMINATE_RESP_RRESP_MASK 0xC

/* PCIE_WRAP_GIC_INTR_TERMINATE_CTRL */
#define PCIE_WRAP_GIC_INTR_TERMINATE_CTRL_BRESP_SHIFT 1
#define PCIE_WRAP_GIC_INTR_TERMINATE_CTRL_BRESP_MASK 0x6
#define PCIE_WRAP_GIC_INTR_TERMINATE_CTRL_STATUS_SHIFT 3
#define PCIE_WRAP_GIC_INTR_TERMINATE_CTRL_STATUS_MASK 0x8

/* PCIE_WRAP_GIC_INTR_TERMINATE_CNT */
#define PCIE_WRAP_GIC_INTR_TERMINATE_CNT_VAL_SHIFT 0
#define PCIE_WRAP_GIC_INTR_TERMINATE_CNT_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_CPU_HOT_RST */
#define PCIE_WRAP_CPU_HOT_RST_CTRL_SHIFT 0
#define PCIE_WRAP_CPU_HOT_RST_CTRL_MASK 0x1

/* PCIE_WRAP_LBW_AXI_SPLIT_MAX_OUTSTAN */
#define PCIE_WRAP_LBW_AXI_SPLIT_MAX_OUTSTAN_RD_SHIFT 0
#define PCIE_WRAP_LBW_AXI_SPLIT_MAX_OUTSTAN_RD_MASK 0xFF
#define PCIE_WRAP_LBW_AXI_SPLIT_MAX_OUTSTAN_WR_SHIFT 8
#define PCIE_WRAP_LBW_AXI_SPLIT_MAX_OUTSTAN_WR_MASK 0xFF00

/* PCIE_WRAP_AXI_SPLIT_NO_WR_INFLIGHT */
#define PCIE_WRAP_AXI_SPLIT_NO_WR_INFLIGHT_MAIN_AXI_SPLIT_IND_SHIFT 0
#define PCIE_WRAP_AXI_SPLIT_NO_WR_INFLIGHT_MAIN_AXI_SPLIT_IND_MASK 0x1
#define PCIE_WRAP_AXI_SPLIT_NO_WR_INFLIGHT_LBW_AXI_SPLIT_IND_SHIFT 1
#define PCIE_WRAP_AXI_SPLIT_NO_WR_INFLIGHT_LBW_AXI_SPLIT_IND_MASK 0x2

/* PCIE_WRAP_PCIE_WR_BUF */
#define PCIE_WRAP_PCIE_WR_BUF_VAL_SHIFT 0
#define PCIE_WRAP_PCIE_WR_BUF_VAL_MASK 0x1

/* PCIE_WRAP_PCIE_CACHE_OVR */
#define PCIE_WRAP_PCIE_CACHE_OVR_RD_SHIFT 0
#define PCIE_WRAP_PCIE_CACHE_OVR_RD_MASK 0xF
#define PCIE_WRAP_PCIE_CACHE_OVR_WR_SHIFT 4
#define PCIE_WRAP_PCIE_CACHE_OVR_WR_MASK 0xF0
#define PCIE_WRAP_PCIE_CACHE_OVR_RD_EN_SHIFT 8
#define PCIE_WRAP_PCIE_CACHE_OVR_RD_EN_MASK 0xF00
#define PCIE_WRAP_PCIE_CACHE_OVR_WR_EN_SHIFT 12
#define PCIE_WRAP_PCIE_CACHE_OVR_WR_EN_MASK 0xF000

/* PCIE_WRAP_PCIE_LOCK_OVR */
#define PCIE_WRAP_PCIE_LOCK_OVR_RD_SHIFT 0
#define PCIE_WRAP_PCIE_LOCK_OVR_RD_MASK 0x1
#define PCIE_WRAP_PCIE_LOCK_OVR_WR_SHIFT 4
#define PCIE_WRAP_PCIE_LOCK_OVR_WR_MASK 0x10
#define PCIE_WRAP_PCIE_LOCK_OVR_RD_EN_SHIFT 8
#define PCIE_WRAP_PCIE_LOCK_OVR_RD_EN_MASK 0x100
#define PCIE_WRAP_PCIE_LOCK_OVR_WR_EN_SHIFT 12
#define PCIE_WRAP_PCIE_LOCK_OVR_WR_EN_MASK 0x1000

/* PCIE_WRAP_PCIE_PROT_OVR */
#define PCIE_WRAP_PCIE_PROT_OVR_RD_SHIFT 0
#define PCIE_WRAP_PCIE_PROT_OVR_RD_MASK 0x7
#define PCIE_WRAP_PCIE_PROT_OVR_WR_SHIFT 4
#define PCIE_WRAP_PCIE_PROT_OVR_WR_MASK 0x70
#define PCIE_WRAP_PCIE_PROT_OVR_RD_EN_SHIFT 8
#define PCIE_WRAP_PCIE_PROT_OVR_RD_EN_MASK 0x700
#define PCIE_WRAP_PCIE_PROT_OVR_WR_EN_SHIFT 12
#define PCIE_WRAP_PCIE_PROT_OVR_WR_EN_MASK 0x7000

/* PCIE_WRAP_PCIE_ARUSER_OVR */
#define PCIE_WRAP_PCIE_ARUSER_OVR_0_ASID_SHIFT 0
#define PCIE_WRAP_PCIE_ARUSER_OVR_0_ASID_MASK 0x3FF
#define PCIE_WRAP_PCIE_ARUSER_OVR_1_ASID_SHIFT 0
#define PCIE_WRAP_PCIE_ARUSER_OVR_1_ASID_MASK 0x3FF
#define PCIE_WRAP_PCIE_ARUSER_OVR_MMU_BYPASS_SHIFT 10
#define PCIE_WRAP_PCIE_ARUSER_OVR_MMU_BYPASS_MASK 0x400
#define PCIE_WRAP_PCIE_ARUSER_OVR_VAL_SHIFT 11
#define PCIE_WRAP_PCIE_ARUSER_OVR_VAL_MASK 0xFFFFF800

/* PCIE_WRAP_PCIE_AWUSER_OVR */
#define PCIE_WRAP_PCIE_AWUSER_OVR_0_ASID_SHIFT 0
#define PCIE_WRAP_PCIE_AWUSER_OVR_0_ASID_MASK 0x3FF
#define PCIE_WRAP_PCIE_AWUSER_OVR_1_ASID_SHIFT 0
#define PCIE_WRAP_PCIE_AWUSER_OVR_1_ASID_MASK 0x3FF
#define PCIE_WRAP_PCIE_AWUSER_OVR_MMU_BYPASS_SHIFT 10
#define PCIE_WRAP_PCIE_AWUSER_OVR_MMU_BYPASS_MASK 0x400
#define PCIE_WRAP_PCIE_AWUSER_OVR_VAL_SHIFT 11
#define PCIE_WRAP_PCIE_AWUSER_OVR_VAL_MASK 0xFFFFF800

/* PCIE_WRAP_PCIE_ARUSER_OVR_EN */
#define PCIE_WRAP_PCIE_ARUSER_OVR_EN_VAL_SHIFT 0
#define PCIE_WRAP_PCIE_ARUSER_OVR_EN_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_PCIE_AWUSER_OVR_EN */
#define PCIE_WRAP_PCIE_AWUSER_OVR_EN_VAL_SHIFT 0
#define PCIE_WRAP_PCIE_AWUSER_OVR_EN_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_PCIE_MAX_OUTSTAND */
#define PCIE_WRAP_PCIE_MAX_OUTSTAND_RD_SHIFT 0
#define PCIE_WRAP_PCIE_MAX_OUTSTAND_RD_MASK 0xFF
#define PCIE_WRAP_PCIE_MAX_OUTSTAND_WR_SHIFT 8
#define PCIE_WRAP_PCIE_MAX_OUTSTAND_WR_MASK 0xFF00

/* PCIE_WRAP_PCIE_MST_IN */
#define PCIE_WRAP_PCIE_MST_IN_AR_SHIFT 0
#define PCIE_WRAP_PCIE_MST_IN_AR_MASK 0x3
#define PCIE_WRAP_PCIE_MST_IN_AW_SHIFT 4
#define PCIE_WRAP_PCIE_MST_IN_AW_MASK 0x30

/* PCIE_WRAP_PCIE_RSP_OK */
#define PCIE_WRAP_PCIE_RSP_OK_IND_SHIFT 0
#define PCIE_WRAP_PCIE_RSP_OK_IND_MASK 0x1

/* PCIE_WRAP_AXI_SPLIT_INTR */
#define PCIE_WRAP_AXI_SPLIT_INTR_IND_SHIFT 0
#define PCIE_WRAP_AXI_SPLIT_INTR_IND_MASK 0x1
#define PCIE_WRAP_AXI_SPLIT_INTR_CLR_SHIFT 1
#define PCIE_WRAP_AXI_SPLIT_INTR_CLR_MASK 0x2

/* PCIE_WRAP_AXI_DRAIN_MSTR_IF_CFG_0 */
#define PCIE_WRAP_AXI_DRAIN_MSTR_IF_CFG_0_CFG_CORE_MODE_SHIFT 24
#define PCIE_WRAP_AXI_DRAIN_MSTR_IF_CFG_0_CFG_CORE_MODE_MASK 0x1000000
#define PCIE_WRAP_AXI_DRAIN_MSTR_IF_CFG_0_CFG_PERM_SEL_SHIFT 25
#define PCIE_WRAP_AXI_DRAIN_MSTR_IF_CFG_0_CFG_PERM_SEL_MASK 0x1E000000
#define PCIE_WRAP_AXI_DRAIN_MSTR_IF_CFG_0_CFG_SCRAM_EXTMEM_EN_SHIFT 29
#define PCIE_WRAP_AXI_DRAIN_MSTR_IF_CFG_0_CFG_SCRAM_EXTMEM_EN_MASK 0x20000000

/* PCIE_WRAP_AXI_DRAIN_EXTMEM_POLY_H3 */
#define PCIE_WRAP_AXI_DRAIN_EXTMEM_POLY_H3_VAL_SHIFT 0
#define PCIE_WRAP_AXI_DRAIN_EXTMEM_POLY_H3_VAL_MASK 0x1FFFFFFF

/* PCIE_WRAP_AXI_DRAIN_ACTIVE */
#define PCIE_WRAP_AXI_DRAIN_ACTIVE_LBW_AXI_DRAIN_ACTIVE_SHIFT 0
#define PCIE_WRAP_AXI_DRAIN_ACTIVE_LBW_AXI_DRAIN_ACTIVE_MASK 0x1
#define PCIE_WRAP_AXI_DRAIN_ACTIVE_HBW_AXI_DRAIN_ACTIVE_SHIFT 1
#define PCIE_WRAP_AXI_DRAIN_ACTIVE_HBW_AXI_DRAIN_ACTIVE_MASK 0x2

/* PCIE_WRAP_AXI_DRAIN_IND */
#define PCIE_WRAP_AXI_DRAIN_IND_LBW_AXI_DRAIN_IND_SHIFT 0
#define PCIE_WRAP_AXI_DRAIN_IND_LBW_AXI_DRAIN_IND_MASK 0x1
#define PCIE_WRAP_AXI_DRAIN_IND_HBW_AXI_DRAIN_IND_SHIFT 1
#define PCIE_WRAP_AXI_DRAIN_IND_HBW_AXI_DRAIN_IND_MASK 0x2

/* PCIE_WRAP_HBW_DRAIN_TIMEOUT */
#define PCIE_WRAP_HBW_DRAIN_TIMEOUT_VAL_SHIFT 0
#define PCIE_WRAP_HBW_DRAIN_TIMEOUT_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_HBW_DRAIN_CFG */
#define PCIE_WRAP_HBW_DRAIN_CFG_EN_SHIFT 0
#define PCIE_WRAP_HBW_DRAIN_CFG_EN_MASK 0x1
#define PCIE_WRAP_HBW_DRAIN_CFG_RSP_SHIFT 4
#define PCIE_WRAP_HBW_DRAIN_CFG_RSP_MASK 0x30

/* PCIE_WRAP_LBW_DRAIN_TIMEOUT */
#define PCIE_WRAP_LBW_DRAIN_TIMEOUT_VAL_SHIFT 0
#define PCIE_WRAP_LBW_DRAIN_TIMEOUT_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_LBW_DRAIN_CFG */
#define PCIE_WRAP_LBW_DRAIN_CFG_EN_SHIFT 0
#define PCIE_WRAP_LBW_DRAIN_CFG_EN_MASK 0x1
#define PCIE_WRAP_LBW_DRAIN_CFG_RSP_SHIFT 4
#define PCIE_WRAP_LBW_DRAIN_CFG_RSP_MASK 0x30
#define PCIE_WRAP_LBW_DRAIN_CFG_DELAYED_EN_SHIFT 6
#define PCIE_WRAP_LBW_DRAIN_CFG_DELAYED_EN_MASK 0x40

/* PCIE_WRAP_LBW_DRAIN_DELAY_EN_CNT */
#define PCIE_WRAP_LBW_DRAIN_DELAY_EN_CNT_VAL_SHIFT 0
#define PCIE_WRAP_LBW_DRAIN_DELAY_EN_CNT_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_PHY_FW_FSM */
#define PCIE_WRAP_PHY_FW_FSM_EN_SHIFT 0
#define PCIE_WRAP_PHY_FW_FSM_EN_MASK 0x1
#define PCIE_WRAP_PHY_FW_FSM_FW_READY_SHIFT 1
#define PCIE_WRAP_PHY_FW_FSM_FW_READY_MASK 0x2
#define PCIE_WRAP_PHY_FW_FSM_BYPASS_POLLING_SHIFT 2
#define PCIE_WRAP_PHY_FW_FSM_BYPASS_POLLING_MASK 0x4
#define PCIE_WRAP_PHY_FW_FSM_DIRECT_WRITE_EN_SHIFT 3
#define PCIE_WRAP_PHY_FW_FSM_DIRECT_WRITE_EN_MASK 0x8
#define PCIE_WRAP_PHY_FW_FSM_ALL_PHY_EXT_LD_DONE_EN_SHIFT 4
#define PCIE_WRAP_PHY_FW_FSM_ALL_PHY_EXT_LD_DONE_EN_MASK 0x10
#define PCIE_WRAP_PHY_FW_FSM_RD_CNTR_SHIFT 5
#define PCIE_WRAP_PHY_FW_FSM_RD_CNTR_MASK 0x1FFFE0

/* PCIE_WRAP_PCIE_PHY_BASE_ADDR_L */
#define PCIE_WRAP_PCIE_PHY_BASE_ADDR_L_VAL_SHIFT 0
#define PCIE_WRAP_PCIE_PHY_BASE_ADDR_L_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_PCIE_PHY_BASE_ADDR_H */
#define PCIE_WRAP_PCIE_PHY_BASE_ADDR_H_VAL_SHIFT 0
#define PCIE_WRAP_PCIE_PHY_BASE_ADDR_H_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_PCIE_CORE_BASE_ADDR_L */
#define PCIE_WRAP_PCIE_CORE_BASE_ADDR_L_VAL_SHIFT 0
#define PCIE_WRAP_PCIE_CORE_BASE_ADDR_L_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_PCIE_CORE_BASE_ADDR_H */
#define PCIE_WRAP_PCIE_CORE_BASE_ADDR_H_VAL_SHIFT 0
#define PCIE_WRAP_PCIE_CORE_BASE_ADDR_H_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_SPMU_INTR */
#define PCIE_WRAP_SPMU_INTR_IND_SHIFT 0
#define PCIE_WRAP_SPMU_INTR_IND_MASK 0x1

/* PCIE_WRAP_AXI_INTR */
#define PCIE_WRAP_AXI_INTR_IND_SHIFT 0
#define PCIE_WRAP_AXI_INTR_IND_MASK 0x1

/* PCIE_WRAP_PCIE_IC_SEI_INTR_IND */
#define PCIE_WRAP_PCIE_IC_SEI_INTR_IND_AXI_ERR_INTR_SHIFT 0
#define PCIE_WRAP_PCIE_IC_SEI_INTR_IND_AXI_ERR_INTR_MASK 0x1
#define PCIE_WRAP_PCIE_IC_SEI_INTR_IND_AXI_LBW_ERR_INTR_SHIFT 1
#define PCIE_WRAP_PCIE_IC_SEI_INTR_IND_AXI_LBW_ERR_INTR_MASK 0x2
#define PCIE_WRAP_PCIE_IC_SEI_INTR_IND_BAD_ACCESS_INTR_SHIFT 2
#define PCIE_WRAP_PCIE_IC_SEI_INTR_IND_BAD_ACCESS_INTR_MASK 0x4
#define PCIE_WRAP_PCIE_IC_SEI_INTR_IND_AXI_ERR_INTR_MASK_SHIFT 3
#define PCIE_WRAP_PCIE_IC_SEI_INTR_IND_AXI_ERR_INTR_MASK_MASK 0x8
#define PCIE_WRAP_PCIE_IC_SEI_INTR_IND_AXI_LBW_ERR_INTR_MASK_SHIFT 4
#define PCIE_WRAP_PCIE_IC_SEI_INTR_IND_AXI_LBW_ERR_INTR_MASK_MASK 0x10
#define PCIE_WRAP_PCIE_IC_SEI_INTR_IND_BAD_ACCESS_INTR_MASK_SHIFT 5
#define PCIE_WRAP_PCIE_IC_SEI_INTR_IND_BAD_ACCESS_INTR_MASK_MASK 0x20

/* PCIE_WRAP_PMMU_RTR_CFG */
#define PCIE_WRAP_PMMU_RTR_CFG_PCIE_RTR_SHIFT 0
#define PCIE_WRAP_PMMU_RTR_CFG_PCIE_RTR_MASK 0x1
#define PCIE_WRAP_PMMU_RTR_CFG_BINNING_SHIFT 1
#define PCIE_WRAP_PMMU_RTR_CFG_BINNING_MASK 0x6

/* PCIE_WRAP_PSOC_RST_CTRL */
#define PCIE_WRAP_PSOC_RST_CTRL_HARD_RST_SHIFT 0
#define PCIE_WRAP_PSOC_RST_CTRL_HARD_RST_MASK 0x1
#define PCIE_WRAP_PSOC_RST_CTRL_SOFT_RST_SHIFT 1
#define PCIE_WRAP_PSOC_RST_CTRL_SOFT_RST_MASK 0x2

/* PCIE_WRAP_PSOC_BOOT_MNG_DONE */
#define PCIE_WRAP_PSOC_BOOT_MNG_DONE_PSOC_BOOT_MNG_DONE_SHIFT 0
#define PCIE_WRAP_PSOC_BOOT_MNG_DONE_PSOC_BOOT_MNG_DONE_MASK 0x1

/* PCIE_WRAP_ASID_MOD_CTRL */
#define PCIE_WRAP_ASID_MOD_CTRL_ASID_SHIFT 0
#define PCIE_WRAP_ASID_MOD_CTRL_ASID_MASK 0x3FF
#define PCIE_WRAP_ASID_MOD_CTRL_MMBP_SHIFT 10
#define PCIE_WRAP_ASID_MOD_CTRL_MMBP_MASK 0x400
#define PCIE_WRAP_ASID_MOD_CTRL_EN_SHIFT 11
#define PCIE_WRAP_ASID_MOD_CTRL_EN_MASK 0x800

/* PCIE_WRAP_ASID_MOD_ADDR_L */
#define PCIE_WRAP_ASID_MOD_ADDR_L_VAL_SHIFT 0
#define PCIE_WRAP_ASID_MOD_ADDR_L_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_ASID_MOD_ADDR_H */
#define PCIE_WRAP_ASID_MOD_ADDR_H_VAL_SHIFT 0
#define PCIE_WRAP_ASID_MOD_ADDR_H_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_CS_TRACE_AXI_CTRL */
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_MASTER_ID_SHIFT 0
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_MASTER_ID_MASK 0x3F
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_EV_IS_GRNT_SHIFT 6
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_EV_IS_GRNT_MASK 0x40
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_EV_IS_DATA_SHIFT 7
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_EV_IS_DATA_MASK 0x80
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_EV_IS_TS_SHIFT 8
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_EV_IS_TS_MASK 0x100
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_EV_IS_MARKED_SHIFT 9
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_EV_IS_MARKED_MASK 0x200
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_EV_CAUSE_TRIG_SHIFT 10
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_EV_CAUSE_TRIG_MASK 0x400
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_DROP_INTR_SHIFT 11
#define PCIE_WRAP_CS_TRACE_AXI_CTRL_DROP_INTR_MASK 0x800

/* PCIE_WRAP_FLR_FSM_CTRL */
#define PCIE_WRAP_FLR_FSM_CTRL_FSM_EN_SHIFT 0
#define PCIE_WRAP_FLR_FSM_CTRL_FSM_EN_MASK 0x1
#define PCIE_WRAP_FLR_FSM_CTRL_FSM_EN_ISO_SHIFT 1
#define PCIE_WRAP_FLR_FSM_CTRL_FSM_EN_ISO_MASK 0x2
#define PCIE_WRAP_FLR_FSM_CTRL_FSM_WAIT_UPSTREAM_TRANS_SHIFT 2
#define PCIE_WRAP_FLR_FSM_CTRL_FSM_WAIT_UPSTREAM_TRANS_MASK 0x4
#define PCIE_WRAP_FLR_FSM_CTRL_FSM_WAIT_BOOT_MNG_DONE_SHIFT 3
#define PCIE_WRAP_FLR_FSM_CTRL_FSM_WAIT_BOOT_MNG_DONE_MASK 0x8
#define PCIE_WRAP_FLR_FSM_CTRL_FSM_PCIE2PSOC_RST_SET_SHIFT 4
#define PCIE_WRAP_FLR_FSM_CTRL_FSM_PCIE2PSOC_RST_SET_MASK 0x10

/* PCIE_WRAP_HBW_DRAIN_WR_ADDR */
#define PCIE_WRAP_HBW_DRAIN_WR_ADDR_VAL_SHIFT 0
#define PCIE_WRAP_HBW_DRAIN_WR_ADDR_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_HBW_DRAIN_RD_ADDR */
#define PCIE_WRAP_HBW_DRAIN_RD_ADDR_VAL_SHIFT 0
#define PCIE_WRAP_HBW_DRAIN_RD_ADDR_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_HBW_DRAIN_STAMP */
#define PCIE_WRAP_HBW_DRAIN_STAMP_EN_SHIFT 0
#define PCIE_WRAP_HBW_DRAIN_STAMP_EN_MASK 0x1

/* PCIE_WRAP_LBW_DRAIN_WR_ADDR */
#define PCIE_WRAP_LBW_DRAIN_WR_ADDR_VAL_SHIFT 0
#define PCIE_WRAP_LBW_DRAIN_WR_ADDR_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_LBW_DRAIN_RD_ADDR */
#define PCIE_WRAP_LBW_DRAIN_RD_ADDR_VAL_SHIFT 0
#define PCIE_WRAP_LBW_DRAIN_RD_ADDR_VAL_MASK 0xFFFFFFFF

/* PCIE_WRAP_LBW_DRAIN_STAMP */
#define PCIE_WRAP_LBW_DRAIN_STAMP_EN_SHIFT 0
#define PCIE_WRAP_LBW_DRAIN_STAMP_EN_MASK 0x1

/* PCIE_WRAP_EXTMEM_HBM_LOC */
#define PCIE_WRAP_EXTMEM_HBM_LOC_HBM0_LOC_SHIFT 0
#define PCIE_WRAP_EXTMEM_HBM_LOC_HBM0_LOC_MASK 0x3F
#define PCIE_WRAP_EXTMEM_HBM_LOC_HBM1_LOC_SHIFT 8
#define PCIE_WRAP_EXTMEM_HBM_LOC_HBM1_LOC_MASK 0x3F00
#define PCIE_WRAP_EXTMEM_HBM_LOC_HBM2_LOC_SHIFT 16
#define PCIE_WRAP_EXTMEM_HBM_LOC_HBM2_LOC_MASK 0x3F0000
#define PCIE_WRAP_EXTMEM_HBM_LOC_USER_SHRD_IND_LOC_SHIFT 24
#define PCIE_WRAP_EXTMEM_HBM_LOC_USER_SHRD_IND_LOC_MASK 0x3F000000

/* PCIE_WRAP_EXTMEM_PC_LOC */
#define PCIE_WRAP_EXTMEM_PC_LOC_PC0_LOC_SHIFT 0
#define PCIE_WRAP_EXTMEM_PC_LOC_PC0_LOC_MASK 0x3F
#define PCIE_WRAP_EXTMEM_PC_LOC_PC1_LOC_SHIFT 8
#define PCIE_WRAP_EXTMEM_PC_LOC_PC1_LOC_MASK 0x3F00
#define PCIE_WRAP_EXTMEM_PC_LOC_PC2_LOC_SHIFT 16
#define PCIE_WRAP_EXTMEM_PC_LOC_PC2_LOC_MASK 0x3F0000
#define PCIE_WRAP_EXTMEM_PC_LOC_PC3_LOC_SHIFT 24
#define PCIE_WRAP_EXTMEM_PC_LOC_PC3_LOC_MASK 0x3F000000

/* PCIE_WRAP_EXTMEM_NONLIN_HBM */
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_CNT_ONE_MASK_SHIFT 0
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_CNT_ONE_MASK_MASK 0xFFFF
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_ALL_ADDR_MASK_SHIFT 16
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_ALL_ADDR_MASK_MASK 0xFF0000
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_CNT_ONE_EN_SHIFT 24
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_CNT_ONE_EN_MASK 0x1000000
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_ALL_ADDR_EN_SHIFT 25
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_ALL_ADDR_EN_MASK 0x2000000

/* PCIE_WRAP_EXTMEM_NONLIN_PC */
#define PCIE_WRAP_EXTMEM_NONLIN_PC_MASK_SHIFT 0
#define PCIE_WRAP_EXTMEM_NONLIN_PC_MASK_MASK 0xFFFF
#define PCIE_WRAP_EXTMEM_NONLIN_PC_EN_SHIFT 16
#define PCIE_WRAP_EXTMEM_NONLIN_PC_EN_MASK 0x10000

/* PCIE_WRAP_EXTMEM_NONLIN_HBM_NUM */
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_NUM_VAL_SHIFT 0
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_NUM_VAL_MASK 0x7

/* PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP */
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP_HBM0_SHIFT 0
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP_HBM0_MASK 0x7
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP_HBM1_SHIFT 4
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP_HBM1_MASK 0x70
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP_HBM2_SHIFT 8
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP_HBM2_MASK 0x700
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP_HBM3_SHIFT 12
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP_HBM3_MASK 0x7000
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP_HBM4_SHIFT 16
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP_HBM4_MASK 0x70000
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP_HBM5_SHIFT 20
#define PCIE_WRAP_EXTMEM_NONLIN_HBM_MAP_HBM5_MASK 0x700000

#endif /* ASIC_REG_PCIE_WRAP_MASKS_H_ */
